# Usa la imagen oficial de WildFly
FROM quay.io/wildfly/wildfly:27.0.0.Final-jdk17

# Establece el directorio de trabajo dentro del contenedor
WORKDIR /opt/jboss/wildfly/standalone/deployments/

# Copia el archivo WAR de tu aplicación al contenedor
COPY target/project-spring-web.war /opt/jboss/wildfly/standalone/deployments/

# Exponer el puerto que usa WildFly (ajústalo a tu configuración)
EXPOSE 8080

# Usa el comando por defecto para iniciar WildFly
CMD ["/opt/jboss/wildfly/bin/standalone.sh", "-b", "0.0.0.0"]

#docker build -t prueba . -f .\Dockerfile
#docker run -p 8080:8080 prueba

